import localFont from "next/font/local";
import "./globals.css";
import { createContext } from "react";
import CartContainer from "./CartContainer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export const CartContext = createContext([])

export default function layout(){
  const cartItems = [
    {id: 1},
    {id: 2},
    {id: 3},
    {id: 4},
    {id: 5},
    {id: 6},
    {id: 7},
    {id: 8},
    {id: 9},
    {id: 10},
    {id: 11},
    {id: 12},
    {id: 13},
    {id: 14},
    {id: 15},
    {id: 16},
    {id: 17},
    {id: 18},
    {id: 19},
    {id: 20}
  ]
  return(
    <main className="layout">
      <CartContext.Provider value = {cartItems}>
        <CartContainer/>
      </CartContext.Provider>
    </main>
  )
}
